[package]
name = "marinfetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cliprint = { path = "../cliprint", features = ["color"] }
users = "0.11.0"
zbus = "3.11.0"
nu-ansi-term = "0.48.0"
